In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer
from sklearn.ensemble import RandomForestClassifier

In [4]:
data = pd.read_csv('passwordData.csv', error_bad_lines= False)
data.head()

C:\Users\lenovo\AppData\Local\Temp\ipykernel_9896\1522359669.py:1: FutureWarning: The error_bad_lines argument has been deprecated and will be removed in a future version. Use on_bad_lines in the future.


  data = pd.read_csv('passwordData.csv', error_bad_lines= False)
Skipping line 2810: expected 2 fields, saw 5
Skipping line 4641: expected 2 fields, saw 5
Skipping line 7171: expected 2 fields, saw 5
Skipping line 11220: expected 2 fields, saw 5
Skipping line 13809: expected 2 fields, saw 5
Skipping line 14132: expected 2 fields, saw 5
Skipping line 14293: expected 2 fields, saw 5
Skipping line 14865: expected 2 fields, saw 5
Skipping line 17419: expected 2 fields, saw 5
Skipping line 22801: expected 2 fields, saw 5
Skipping line 25001: expected 2 fields, saw 5
Skipping line 26603: expected 2 fields, saw 5
Skipping line 26742: expected 2 fields, saw 5
Skipping line 29702: expected 2 fields, saw 5
Skipping line 32767: expected 2 fields, saw 5
Skipping line 32878: expected 2 fields, saw 5
Skipping line 35643: expected 2 fields, saw 5
Skipping line 36550: expected 2 fields, saw 5
Skipping line 38732: expected 2 fields, saw 5
Skipping line 40567: expected 2 fields, saw 5
Skipping line 40576: expected 2 fields, saw 5
Skipping line 41864: expected 2 fields, saw 5
Skipping line 46861: expected 2 fields, saw 5
Skipping line 47939: expected 2 fields, saw 5
Skipping line 48628: expected 2 fields, saw 5
Skipping line 48908: expected 2 fields, saw 5
Skipping line 57582: expected 2 fields, saw 5
Skipping line 58782: expected 2 fields, saw 5
Skipping line 58984: expected 2 fields, saw 5
Skipping line 61518: expected 2 fields, saw 5
Skipping line 63451: expected 2 fields, saw 5
Skipping line 68141: expected 2 fields, saw 5
Skipping line 72083: expected 2 fields, saw 5
Skipping line 74027: expected 2 fields, saw 5
Skipping line 77811: expected 2 fields, saw 5
Skipping line 83958: expected 2 fields, saw 5
Skipping line 85295: expected 2 fields, saw 5
Skipping line 88665: expected 2 fields, saw 5
Skipping line 89198: expected 2 fields, saw 5
Skipping line 92499: expected 2 fields, saw 5
Skipping line 92751: expected 2 fields, saw 5
Skipping line 93689: expected 2 fields, saw 5
Skipping line 94776: expected 2 fields, saw 5
Skipping line 97334: expected 2 fields, saw 5
Skipping line 102316: expected 2 fields, saw 5
Skipping line 103421: expected 2 fields, saw 5
Skipping line 106872: expected 2 fields, saw 5
Skipping line 109363: expected 2 fields, saw 5
Skipping line 110117: expected 2 fields, saw 5
Skipping line 110465: expected 2 fields, saw 5
Skipping line 113843: expected 2 fields, saw 5
Skipping line 115634: expected 2 fields, saw 5
Skipping line 121518: expected 2 fields, saw 5
Skipping line 123692: expected 2 fields, saw 5
Skipping line 124708: expected 2 fields, saw 5
Skipping line 129608: expected 2 fields, saw 5
Skipping line 133176: expected 2 fields, saw 5
Skipping line 135532: expected 2 fields, saw 5
Skipping line 138042: expected 2 fields, saw 5
Skipping line 139485: expected 2 fields, saw 5
Skipping line 140401: expected 2 fields, saw 5
Skipping line 144093: expected 2 fields, saw 5
Skipping line 149850: expected 2 fields, saw 5
Skipping line 151831: expected 2 fields, saw 5
Skipping line 158014: expected 2 fields, saw 5
Skipping line 162047: expected 2 fields, saw 5
Skipping line 164515: expected 2 fields, saw 5
Skipping line 170313: expected 2 fields, saw 5
Skipping line 171325: expected 2 fields, saw 5
Skipping line 171424: expected 2 fields, saw 5
Skipping line 175920: expected 2 fields, saw 5
Skipping line 176210: expected 2 fields, saw 5
Skipping line 183603: expected 2 fields, saw 5
Skipping line 190264: expected 2 fields, saw 5
Skipping line 191683: expected 2 fields, saw 5
Skipping line 191988: expected 2 fields, saw 5
Skipping line 195450: expected 2 fields, saw 5
Skipping line 195754: expected 2 fields, saw 5
Skipping line 197124: expected 2 fields, saw 5
Skipping line 199263: expected 2 fields, saw 5
Skipping line 202603: expected 2 fields, saw 5
Skipping line 209960: expected 2 fields, saw 5
Skipping line 213218: expected 2 fields, saw 5
Skipping line 217060: expected 2 fields, saw 5
Skipping line 220121: expected 2 fields, saw 5
Skipping line 223518: expected 2 fields, saw 5
Skipping line 226293: expected 2 fields, saw 5
Skipping line 227035: expected 2 fields, saw 7
Skipping line 227341: expected 2 fields, saw 5
Skipping line 227808: expected 2 fields, saw 5
Skipping line 228516: expected 2 fields, saw 5
Skipping line 228733: expected 2 fields, saw 5
Skipping line 232043: expected 2 fields, saw 5
Skipping line 232426: expected 2 fields, saw 5
Skipping line 234490: expected 2 fields, saw 5
Skipping line 239626: expected 2 fields, saw 5
Skipping line 240461: expected 2 fields, saw 5
Skipping line 244518: expected 2 fields, saw 5
Skipping line 245395: expected 2 fields, saw 5
Skipping line 246168: expected 2 fields, saw 5
Skipping line 246655: expected 2 fields, saw 5
Skipping line 246752: expected 2 fields, saw 5
Skipping line 247189: expected 2 fields, saw 5
Skipping line 250276: expected 2 fields, saw 5
Skipping line 255327: expected 2 fields, saw 5
Skipping line 257094: expected 2 fields, saw 5

Skipping line 264626: expected 2 fields, saw 5
Skipping line 265028: expected 2 fields, saw 5
Skipping line 269150: expected 2 fields, saw 5
Skipping line 271360: expected 2 fields, saw 5
Skipping line 273975: expected 2 fields, saw 5
Skipping line 274742: expected 2 fields, saw 5
Skipping line 276227: expected 2 fields, saw 5
Skipping line 279807: expected 2 fields, saw 5
Skipping line 283425: expected 2 fields, saw 5
Skipping line 287468: expected 2 fields, saw 5
Skipping line 292995: expected 2 fields, saw 5
Skipping line 293496: expected 2 fields, saw 5
Skipping line 293735: expected 2 fields, saw 5
Skipping line 295060: expected 2 fields, saw 5
Skipping line 296643: expected 2 fields, saw 5
Skipping line 296848: expected 2 fields, saw 5
Skipping line 308926: expected 2 fields, saw 5
Skipping line 310360: expected 2 fields, saw 5
Skipping line 317004: expected 2 fields, saw 5
Skipping line 318207: expected 2 fields, saw 5
Skipping line 331783: expected 2 fields, saw 5
Skipping line 333864: expected 2 fields, saw 5
Skipping line 335958: expected 2 fields, saw 5
Skipping line 336290: expected 2 fields, saw 5
Skipping line 343526: expected 2 fields, saw 5
Skipping line 343857: expected 2 fields, saw 5
Skipping line 344059: expected 2 fields, saw 5
Skipping line 348691: expected 2 fields, saw 5
Skipping line 353446: expected 2 fields, saw 5
Skipping line 357073: expected 2 fields, saw 5
Skipping line 359753: expected 2 fields, saw 5
Skipping line 359974: expected 2 fields, saw 5
Skipping line 366534: expected 2 fields, saw 5
Skipping line 369514: expected 2 fields, saw 5
Skipping line 377759: expected 2 fields, saw 5
Skipping line 379327: expected 2 fields, saw 5
Skipping line 380769: expected 2 fields, saw 5
Skipping line 381073: expected 2 fields, saw 5
Skipping line 381489: expected 2 fields, saw 5
Skipping line 386304: expected 2 fields, saw 5
Skipping line 387635: expected 2 fields, saw 5
Skipping line 389613: expected 2 fields, saw 5
Skipping line 392604: expected 2 fields, saw 5
Skipping line 393184: expected 2 fields, saw 5
Skipping line 395530: expected 2 fields, saw 5
Skipping line 396939: expected 2 fields, saw 5
Skipping line 397385: expected 2 fields, saw 5
Skipping line 397509: expected 2 fields, saw 5
Skipping line 402902: expected 2 fields, saw 5
Skipping line 405187: expected 2 fields, saw 5
Skipping line 408412: expected 2 fields, saw 5
Skipping line 419423: expected 2 fields, saw 5
Skipping line 420962: expected 2 fields, saw 5
Skipping line 425965: expected 2 fields, saw 5
Skipping line 427496: expected 2 fields, saw 5
Skipping line 438881: expected 2 fields, saw 5
Skipping line 439776: expected 2 fields, saw 5
Skipping line 440345: expected 2 fields, saw 5
Skipping line 445507: expected 2 fields, saw 5
Skipping line 445548: expected 2 fields, saw 5
Skipping line 447184: expected 2 fields, saw 5
Skipping line 448603: expected 2 fields, saw 5
Skipping line 451732: expected 2 fields, saw 5
Skipping line 458249: expected 2 fields, saw 5
Skipping line 460274: expected 2 fields, saw 5
Skipping line 467630: expected 2 fields, saw 5
Skipping line 473961: expected 2 fields, saw 5
Skipping line 476281: expected 2 fields, saw 5
Skipping line 478010: expected 2 fields, saw 5
Skipping line 478322: expected 2 fields, saw 5
Skipping line 479999: expected 2 fields, saw 5
Skipping line 480898: expected 2 fields, saw 5
Skipping line 481688: expected 2 fields, saw 5
Skipping line 485193: expected 2 fields, saw 5
Skipping line 485519: expected 2 fields, saw 5
Skipping line 486000: expected 2 fields, saw 5
Skipping line 489063: expected 2 fields, saw 5
Skipping line 494525: expected 2 fields, saw 5
Skipping line 495009: expected 2 fields, saw 5
Skipping line 501954: expected 2 fields, saw 5
Skipping line 508035: expected 2 fields, saw 5
Skipping line 508828: expected 2 fields, saw 5
Skipping line 509833: expected 2 fields, saw 5
Skipping line 510410: expected 2 fields, saw 5
Skipping line 518229: expected 2 fields, saw 5
Skipping line 520302: expected 2 fields, saw 5
Skipping line 520340: expected 2 fields, saw 5

Skipping line 525174: expected 2 fields, saw 5
Skipping line 526251: expected 2 fields, saw 5
Skipping line 529611: expected 2 fields, saw 5
Skipping line 531398: expected 2 fields, saw 5
Skipping line 534146: expected 2 fields, saw 5
Skipping line 544954: expected 2 fields, saw 5
Skipping line 553002: expected 2 fields, saw 5
Skipping line 553883: expected 2 fields, saw 5
Skipping line 553887: expected 2 fields, saw 5
Skipping line 553915: expected 2 fields, saw 5
Skipping line 554172: expected 2 fields, saw 5
Skipping line 563534: expected 2 fields, saw 5
Skipping line 565191: expected 2 fields, saw 5
Skipping line 574108: expected 2 fields, saw 5
Skipping line 574412: expected 2 fields, saw 5
Skipping line 575985: expected 2 fields, saw 5
Skipping line 580091: expected 2 fields, saw 5
Skipping line 582682: expected 2 fields, saw 5
Skipping line 585885: expected 2 fields, saw 5
Skipping line 590171: expected 2 fields, saw 5
Skipping line 591924: expected 2 fields, saw 5
Skipping line 592515: expected 2 fields, saw 5
Skipping line 593888: expected 2 fields, saw 5
Skipping line 596245: expected 2 fields, saw 5
Skipping line 607344: expected 2 fields, saw 5
Skipping line 607633: expected 2 fields, saw 5
Skipping line 610939: expected 2 fields, saw 5
Skipping line 613638: expected 2 fields, saw 5
Skipping line 615643: expected 2 fields, saw 5
Skipping line 615901: expected 2 fields, saw 5
Skipping line 617389: expected 2 fields, saw 5
Skipping line 634641: expected 2 fields, saw 5
Skipping line 635755: expected 2 fields, saw 5
Skipping line 646243: expected 2 fields, saw 5
Skipping line 647165: expected 2 fields, saw 5
Skipping line 648610: expected 2 fields, saw 5
Skipping line 648772: expected 2 fields, saw 5
Skipping line 651833: expected 2 fields, saw 5
Skipping line 653663: expected 2 fields, saw 5
Skipping line 656233: expected 2 fields, saw 5
Skipping line 656694: expected 2 fields, saw 5
Skipping line 659783: expected 2 fields, saw 5
Skipping line 660478: expected 2 fields, saw 5
Skipping line 661133: expected 2 fields, saw 5
Skipping line 661736: expected 2 fields, saw 5
Skipping line 669827: expected 2 fields, saw 5

      password  strength
0     kzde5577         1
1     kino3434         1
2    visi7k1yr         1
3     megzy123         1
4  lamborghin1         1

In [5]:
data.isnull().sum()

password    1
strength    0
dtype: int64

In [6]:
data = data.dropna()
data.isnull().sum()

password    0
strength    0
dtype: int64

In [7]:
data["strength"] = data["strength"].map({0:"Weak",
                                         1:"Medium",
                                         2:"Strong"})
data

            password strength
0           kzde5577   Medium
1           kino3434   Medium
2          visi7k1yr   Medium
3           megzy123   Medium
4        lamborghin1   Medium
...              ...      ...
669635    10redtux10   Medium
669636     infrared1   Medium
669637  184520socram   Medium
669638     marken22a   Medium
669639      fxx4pw4g   Medium

[669639 rows x 2 columns]

In [8]:
data.query("strength == 'Weak'")

       password strength
21       intel1     Weak
35      lsdlsd1     Weak
44       olmaz.     Weak
50       ok>bdk     Weak
58       d04m11     Weak
...         ...      ...
669572  o3kkmwz     Weak
669573  yenni91     Weak
669593  vehlfb8     Weak
669608   mo1152     Weak
669634   sh4tup     Weak

[89701 rows x 2 columns]

In [9]:
data.query("strength == 'Medium'")

            password strength
0           kzde5577   Medium
1           kino3434   Medium
2          visi7k1yr   Medium
3           megzy123   Medium
4        lamborghin1   Medium
...              ...      ...
669635    10redtux10   Medium
669636     infrared1   Medium
669637  184520socram   Medium
669638     marken22a   Medium
669639      fxx4pw4g   Medium

[496801 rows x 2 columns]

In [10]:
data.query("strength == 'Strong'")

                         password strength
5                AVYq1lDE4MgAZfNt   Strong
13               WUt9IZzE0OQ7PkNE   Strong
20            elyass15@ajilent-ci   Strong
22               klara-tershina3H   Strong
41               pHyqueDIyNQ8vmhb   Strong
...                           ...      ...
669618  juanpaganini588@gmail.com   Strong
669619           tYAam8zg3Mg2AZ7a   Strong
669622           weslley.06888524   Strong
669627             sakaryal&#305;   Strong
669631           8rp4PTTM1MAlcLw0   Strong

[83137 rows x 2 columns]

In [12]:
def words(password):
    char = []
    for i in password:
        char.append(i)
    return char

x = np.array(data["password"])
y = np.array(data['strength'])
tdif = TfidfVectorizer(tokenizer=words)
x = tdif.fit_transform(x)
xtrain, xtest, ytrain, ytest = train_test_split(x,y, test_size=0.4, random_state=42)

In [13]:
xtrain

<401783x153 sparse matrix of type '<class 'numpy.float64'>'
	with 3384814 stored elements in Compressed Sparse Row format>

In [14]:
model = RandomForestClassifier()
model.fit(xtrain,ytrain)

RandomForestClassifier()

In [16]:
ypred = model.predict(xtest)
ypred

array(['Medium', 'Medium', 'Strong', ..., 'Medium', 'Medium', 'Medium'],
      dtype=object)

In [17]:
from sklearn.metrics import accuracy_score
accuracy = accuracy_score(ytest, ypred)
print(f"Model accuracy: {accuracy*100}%")

Model accuracy: 95.2284063078669%

In [26]:
import getpass
user = getpass.getpass("Enter Password: ")
data = tdif.transform([user]).toarray()
output = model.predict(data)
print(output)

['Medium']